default:
  navigation:
    - title: MENÚ
      subtitle: Categories
      url: /t/menu
      promo_banners:
        - subtitle: ''
          title: ''
          url: /t/promociones
          image: 'https://i.ibb.co/SKd8RL6/cover-web.png'
        - subtitle: ''
          title: ''
          url: /t/promociones
          image: 'https://i.ibb.co/XWqNVC9/banner.png'
    - title: UBICACIONES
      subtitle: Categories
      url: /ubicaciones
    - title: EVENTOS
      subtitle: Categories
      url: /eventos
    - title: PROMOCIONES
      subtitle: Categories
      url: /t/promociones
    - title: CONTACTO
      subtitle: Categories
      url: /contacto
     