default:
  navigation:
    - title: Nuestro Menú
      subtitle: Categories
      url: /t/nuestro_menu
      items:
        - :title: Pizzas
          :url: /t/nuestro_menu/pizzas
        - :title: Acompañantes
          :url: /t/nuestro_menu/acompañantes
        - :title: Promociones
          :url: /t/nuestro_menu/promociones
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Nuestra Historia
      subtitle:
      url:
      items:
    - title: Restaurantes
      subtitle: 
      url: 
      items: